// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "coindrop-ap": paycheck Resource Client
//
// Command:
// $ goagen
// --design=github.com/waymobetta/go-coindrop-ap-server/design
// --out=$(GOPATH)/src/github.com/waymobetta/go-coindrop-ap-server
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// SendPaycheckPath computes a request path to the send action of paycheck.
func SendPaycheckPath() string {

	return fmt.Sprintf("/v1/paycheck")
}

// Sends ethereum wallet token amount
func (c *Client) SendPaycheck(ctx context.Context, path string, payload *PaycheckPayload, contentType string) (*http.Response, error) {
	req, err := c.NewSendPaycheckRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSendPaycheckRequest create the request corresponding to the send action endpoint of the paycheck resource.
func (c *Client) NewSendPaycheckRequest(ctx context.Context, path string, payload *PaycheckPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
