// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "coindrop-ap": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/waymobetta/go-coindrop-ap-server/design
// --out=$(GOPATH)/src/github.com/waymobetta/go-coindrop-ap-server
// --version=v1.3.1

package app

// HealthcheckHref returns the resource href.
func HealthcheckHref() string {
	return "/v1/healthcheck"
}
