// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "coindrop-ap": Application User Types
//
// Command:
// $ goagen
// --design=github.com/waymobetta/go-coindrop-ap-server/design
// --out=$(GOPATH)/src/github.com/waymobetta/go-coindrop-ap-server
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// Paycheck payload
type paycheckPayload struct {
	// ethereum address
	EthereumAddress *string `form:"ethereumAddress,omitempty" json:"ethereumAddress,omitempty" yaml:"ethereumAddress,omitempty" xml:"ethereumAddress,omitempty"`
	// token amount
	TokenAmount *int `form:"tokenAmount,omitempty" json:"tokenAmount,omitempty" yaml:"tokenAmount,omitempty" xml:"tokenAmount,omitempty"`
}

// Validate validates the paycheckPayload type instance.
func (ut *paycheckPayload) Validate() (err error) {
	if ut.EthereumAddress == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`request`, "ethereumAddress"))
	}
	if ut.TokenAmount == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`request`, "tokenAmount"))
	}
	return
}

// Publicize creates PaycheckPayload from paycheckPayload
func (ut *paycheckPayload) Publicize() *PaycheckPayload {
	var pub PaycheckPayload
	if ut.EthereumAddress != nil {
		pub.EthereumAddress = *ut.EthereumAddress
	}
	if ut.TokenAmount != nil {
		pub.TokenAmount = *ut.TokenAmount
	}
	return &pub
}

// Paycheck payload
type PaycheckPayload struct {
	// ethereum address
	EthereumAddress string `form:"ethereumAddress" json:"ethereumAddress" yaml:"ethereumAddress" xml:"ethereumAddress"`
	// token amount
	TokenAmount int `form:"tokenAmount" json:"tokenAmount" yaml:"tokenAmount" xml:"tokenAmount"`
}

// Validate validates the PaycheckPayload type instance.
func (ut *PaycheckPayload) Validate() (err error) {
	if ut.EthereumAddress == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`type`, "ethereumAddress"))
	}

	return
}
